{
 "title": "Openshift GitOps (ArgoCD) Dashboard",
 "description": "Monitor ArgoCD applications on OpenShift, including sync status, memory/CPU usage, gRPC calls, errors, and repositories using Grafana.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(argocd_app_info,namespace)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   { "name": "grouping", "query": "namespace,name,project" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(argocd_cluster_info, server)"
    }
   },
   {
    "name": "health_status",
    "query": {
     "query": "query_result(sum(argocd_app_info) by (health_status))"
    }
   },
   {
    "name": "sync_status",
    "query": {
     "query": "query_result(sum(argocd_app_info) by (sync_status))"
    }
   },
   {
    "name": "argocd_url",
    "label": "host",
    "query": {
     "query": "query_result(openshift_route_status{namespace=\"openshift-gitops\", route=\"openshift-gitops-server\"})"
    }
   },
   {
    "name": "badge_name",
    "label": "badge_name",
    "query": {
     "query": "query_result(sum(argocd_app_info) by (name))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "⏳ Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_start_time{namespace=\"openshift-gitops\", pod=~\"openshift-gitops-server-.*\"}"
    }
   ]
  },
  {
   "title": "📦 Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\"})"
    }
   ]
  },
  {
   "title": "🔗 Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "🔄 Sync Success vs Failures (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(argocd_app_sync_total{namespace=~'$namespace'}[24h])))",
     "legendFormat": "Total Syncs"
    },
    {
     "expr": "round(sum(increase(argocd_app_sync_total{namespace=~'$namespace', phase='Error'}[24h])))",
     "legendFormat": "Failed Syncs"
    },
    {
     "expr": "round(sum(increase(argocd_app_sync_total{namespace=~'$namespace', phase='Succeeded'}[24h])))",
     "legendFormat": "Succeeded Syncs"
    }
   ]
  },
  {
   "title": "📋 ArgoCD Applications Sync Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(\n              argocd_app_info{\n                  namespace=~'$namespace',\n                  dest_server=~'$cluster',\n                  health_status!~\"\",\n                  sync_status!~\"\"\n              }\n          ) by (name, health_status, sync_status, last_sync_time)"
    }
   ]
  },
  {
   "title": "📋 ArgoCD Auto-Sync Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace='openshift-gitops'}) by (name, autosync_enabled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔄 Sync Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "❤️ Health Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Git Requests (ls-remote & checkout)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\", namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "ls-remote - {{namespace}}"
    },
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\", namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "fetch - {{namespace}}"
    },
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"checkout\", namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "checkout - {{namespace}}"
    }
   ]
  },
  {
   "title": "Git Requests (checkout)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\", namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "ArgoCD CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu', pod=~'openshift-gitops-server-.*', namespace='openshift-gitops'}) BY (pod)",
     "legendFormat": "Request - {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu', pod=~'openshift-gitops-server-.*', namespace='openshift-gitops'}) BY (pod)",
     "legendFormat": "Limit - {{pod}}"
    },
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"openshift-gitops\",pod=~\"openshift-gitops-server-.*\"}",
     "legendFormat": "Usage - {{pod}}"
    }
   ]
  },
  {
   "title": "ArgoCD Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource='memory', pod=~'openshift-gitops-server-.*', namespace='openshift-gitops'}) BY (pod)",
     "legendFormat": "Request - {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory', pod=~'openshift-gitops-server-.*', namespace='openshift-gitops'}) BY (pod)",
     "legendFormat": "Limit - {{pod}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'openshift-gitops-server-.*', namespace='openshift-gitops', container=''}) BY (pod)",
     "legendFormat": "Usage - {{pod}}"
    }
   ]
  },
  {
   "title": "📡 OpenShift API Request Latency (HAProxy)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route='openshift-gitops-server'}[5m])) by (code)",
     "legendFormat": "HTTP Code {{code}}"
    }
   ]
  },
  {
   "title": "ArgoCD Heap Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job='openshift-gitops-server-metrics', namespace=~'$namespace'}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "ArgoCD gRPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"application.ApplicationService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "RepositoryService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"openshift-gitops-server-metrics\",grpc_service=\"repository.RepositoryService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}}-{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Reconciliation Activity by Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_count{namespace=~\"$namespace\",dest_server=~\"$cluster\"}[$interval])) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Reconciliation Bucket Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "Reconciliation Activity by Bucket"
    }
   ]
  },
  {
   "title": "Redis Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(argocd_redis_request_total{namespace=~\"$namespace\"}[$interval])) by (failed)",
     "legendFormat": "{{failed}}"
    }
   ]
  }
 ]
}