---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: grafana-sa
  namespace: openshift-user-workload-monitoring
  labels:
    app: grafana-sa
    app.kubernetes.io/instance: grafana-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-a-sa-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: grafana-a-sa
  namespace: openshift-user-workload-monitoring
- kind: ServiceAccount
  name: grafana-sa
  namespace: openshift-user-workload-monitoring
